// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/billing/billing.proto

package billing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReservePromptSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservePromptSlotRequest) Reset() {
	*x = ReservePromptSlotRequest{}
	mi := &file_proto_billing_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservePromptSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservePromptSlotRequest) ProtoMessage() {}

func (x *ReservePromptSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservePromptSlotRequest.ProtoReflect.Descriptor instead.
func (*ReservePromptSlotRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_billing_proto_rawDescGZIP(), []int{0}
}

func (x *ReservePromptSlotRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ReservePromptSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservePromptSlotResponse) Reset() {
	*x = ReservePromptSlotResponse{}
	mi := &file_proto_billing_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservePromptSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservePromptSlotResponse) ProtoMessage() {}

func (x *ReservePromptSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservePromptSlotResponse.ProtoReflect.Descriptor instead.
func (*ReservePromptSlotResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_billing_proto_rawDescGZIP(), []int{1}
}

type ReleasePromptSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleasePromptSlotRequest) Reset() {
	*x = ReleasePromptSlotRequest{}
	mi := &file_proto_billing_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleasePromptSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleasePromptSlotRequest) ProtoMessage() {}

func (x *ReleasePromptSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleasePromptSlotRequest.ProtoReflect.Descriptor instead.
func (*ReleasePromptSlotRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_billing_proto_rawDescGZIP(), []int{2}
}

func (x *ReleasePromptSlotRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ReleasePromptSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleasePromptSlotResponse) Reset() {
	*x = ReleasePromptSlotResponse{}
	mi := &file_proto_billing_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleasePromptSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleasePromptSlotResponse) ProtoMessage() {}

func (x *ReleasePromptSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleasePromptSlotResponse.ProtoReflect.Descriptor instead.
func (*ReleasePromptSlotResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_billing_proto_rawDescGZIP(), []int{3}
}

var File_proto_billing_billing_proto protoreflect.FileDescriptor

const file_proto_billing_billing_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/billing/billing.proto\x12\abilling\"3\n" +
	"\x18ReservePromptSlotRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x1b\n" +
	"\x19ReservePromptSlotResponse\"3\n" +
	"\x18ReleasePromptSlotRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x1b\n" +
	"\x19ReleasePromptSlotResponse2\xc5\x01\n" +
	"\aBilling\x12\\\n" +
	"\x11ReservePromptSlot\x12!.billing.ReservePromptSlotRequest\x1a\".billing.ReservePromptSlotResponse\"\x00\x12\\\n" +
	"\x11ReleasePromptSlot\x12!.billing.ReleasePromptSlotRequest\x1a\".billing.ReleasePromptSlotResponse\"\x00B;Z9github.com/DavidOrtegaFarrerons/promptforge/proto/billingb\x06proto3"

var (
	file_proto_billing_billing_proto_rawDescOnce sync.Once
	file_proto_billing_billing_proto_rawDescData []byte
)

func file_proto_billing_billing_proto_rawDescGZIP() []byte {
	file_proto_billing_billing_proto_rawDescOnce.Do(func() {
		file_proto_billing_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_billing_billing_proto_rawDesc), len(file_proto_billing_billing_proto_rawDesc)))
	})
	return file_proto_billing_billing_proto_rawDescData
}

var file_proto_billing_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_billing_billing_proto_goTypes = []any{
	(*ReservePromptSlotRequest)(nil),  // 0: billing.ReservePromptSlotRequest
	(*ReservePromptSlotResponse)(nil), // 1: billing.ReservePromptSlotResponse
	(*ReleasePromptSlotRequest)(nil),  // 2: billing.ReleasePromptSlotRequest
	(*ReleasePromptSlotResponse)(nil), // 3: billing.ReleasePromptSlotResponse
}
var file_proto_billing_billing_proto_depIdxs = []int32{
	0, // 0: billing.Billing.ReservePromptSlot:input_type -> billing.ReservePromptSlotRequest
	2, // 1: billing.Billing.ReleasePromptSlot:input_type -> billing.ReleasePromptSlotRequest
	1, // 2: billing.Billing.ReservePromptSlot:output_type -> billing.ReservePromptSlotResponse
	3, // 3: billing.Billing.ReleasePromptSlot:output_type -> billing.ReleasePromptSlotResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_billing_billing_proto_init() }
func file_proto_billing_billing_proto_init() {
	if File_proto_billing_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_billing_billing_proto_rawDesc), len(file_proto_billing_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_billing_billing_proto_goTypes,
		DependencyIndexes: file_proto_billing_billing_proto_depIdxs,
		MessageInfos:      file_proto_billing_billing_proto_msgTypes,
	}.Build()
	File_proto_billing_billing_proto = out.File
	file_proto_billing_billing_proto_goTypes = nil
	file_proto_billing_billing_proto_depIdxs = nil
}
