// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/billing/billing.proto

package billing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Billing_ReservePromptSlot_FullMethodName = "/billing.Billing/ReservePromptSlot"
	Billing_ReleasePromptSlot_FullMethodName = "/billing.Billing/ReleasePromptSlot"
)

// BillingClient is the client API for Billing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillingClient interface {
	ReservePromptSlot(ctx context.Context, in *ReservePromptSlotRequest, opts ...grpc.CallOption) (*ReservePromptSlotResponse, error)
	ReleasePromptSlot(ctx context.Context, in *ReleasePromptSlotRequest, opts ...grpc.CallOption) (*ReleasePromptSlotResponse, error)
}

type billingClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingClient(cc grpc.ClientConnInterface) BillingClient {
	return &billingClient{cc}
}

func (c *billingClient) ReservePromptSlot(ctx context.Context, in *ReservePromptSlotRequest, opts ...grpc.CallOption) (*ReservePromptSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReservePromptSlotResponse)
	err := c.cc.Invoke(ctx, Billing_ReservePromptSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingClient) ReleasePromptSlot(ctx context.Context, in *ReleasePromptSlotRequest, opts ...grpc.CallOption) (*ReleasePromptSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleasePromptSlotResponse)
	err := c.cc.Invoke(ctx, Billing_ReleasePromptSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServer is the server API for Billing service.
// All implementations must embed UnimplementedBillingServer
// for forward compatibility.
type BillingServer interface {
	ReservePromptSlot(context.Context, *ReservePromptSlotRequest) (*ReservePromptSlotResponse, error)
	ReleasePromptSlot(context.Context, *ReleasePromptSlotRequest) (*ReleasePromptSlotResponse, error)
	mustEmbedUnimplementedBillingServer()
}

// UnimplementedBillingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingServer struct{}

func (UnimplementedBillingServer) ReservePromptSlot(context.Context, *ReservePromptSlotRequest) (*ReservePromptSlotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReservePromptSlot not implemented")
}
func (UnimplementedBillingServer) ReleasePromptSlot(context.Context, *ReleasePromptSlotRequest) (*ReleasePromptSlotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleasePromptSlot not implemented")
}
func (UnimplementedBillingServer) mustEmbedUnimplementedBillingServer() {}
func (UnimplementedBillingServer) testEmbeddedByValue()                 {}

// UnsafeBillingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServer will
// result in compilation errors.
type UnsafeBillingServer interface {
	mustEmbedUnimplementedBillingServer()
}

func RegisterBillingServer(s grpc.ServiceRegistrar, srv BillingServer) {
	// If the following call panics, it indicates UnimplementedBillingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Billing_ServiceDesc, srv)
}

func _Billing_ReservePromptSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReservePromptSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServer).ReservePromptSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Billing_ReservePromptSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServer).ReservePromptSlot(ctx, req.(*ReservePromptSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Billing_ReleasePromptSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleasePromptSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServer).ReleasePromptSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Billing_ReleasePromptSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServer).ReleasePromptSlot(ctx, req.(*ReleasePromptSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Billing_ServiceDesc is the grpc.ServiceDesc for Billing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Billing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing.Billing",
	HandlerType: (*BillingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReservePromptSlot",
			Handler:    _Billing_ReservePromptSlot_Handler,
		},
		{
			MethodName: "ReleasePromptSlot",
			Handler:    _Billing_ReleasePromptSlot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/billing/billing.proto",
}
